env:
  browser: true
  es2021: true
  jquery: true
extends:
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - 'jquery'
rules: {}
